# Generated by Django 3.2.4 on 2021-09-13 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0002_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uploadapp.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='uploadapp.user')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
