# Generated by Django 3.2.4 on 2021-08-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0003_auto_20210821_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicionlogo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='posicionlogo',
            name='posicion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='posicionlogo',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
