# Generated by Django 3.2.4 on 2021-09-13 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0004_auto_20210913_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': False},
        ),
    ]
