# Generated by Django 3.2.4 on 2021-08-27 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0004_auto_20210821_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('nit', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('logo', models.CharField(max_length=100, null=True)),
                ('slogan', models.CharField(max_length=500, null=True)),
                ('cantidad_facturas_mensual', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('correo', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('estado', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='posicionlogo',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posicionlogo',
            name='usuario',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
