# Generated by Django 3.2.4 on 2021-09-13 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0005_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
    ]
