# Generated by Django 3.2.4 on 2021-09-13 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0006_alter_profile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
